sugar_url: http://test
sugar_username: test
sugar_password: test

salesforce_consumer_key: test..test
salesforce_consumer_secret: test
salesforce_username: test
salesforce_password: test

db_type: mysql2
db_user: test
db_password: 'test'
db_database: sugar
