sugar_url: http://localhost/agent_portal
sugar_username: admin
sugar_password: admin

salesforce_consumer_key: 3MVG99OxTyEMCQ3iHECRgt94iuLGpB20PtwoWc0LbU0P9S..tH7udaM8sQqhKQkvKki2dQBkdKiGwGGJ0NaGU
salesforce_consumer_secret: 9068472962079698210
salesforce_username: stefan@emerchantpay.com
salesforce_password: wizardone1234JTh7sjIcRY7B9l9smdKiTjfGi

db_type: mysql2
db_user: root
db_password: '123456'
db_database: agent_portal
